language: node_js
node_js:
- '0.12'
- '4.0'
- '4.1'
- '4.2'
- '5.0'
- '5.1'
- '5.2'
- '5.3'
- '5.4'
os:
- linux
- osx
matrix:
  fast_finish: true
before_install:
- npm install -g grunt-cli
deploy:
- provider: npm
  skip_cleanup: true
  email: pact-foundation@googlegroups.com
  api_key:
    secure: VfU92fkX9T+qtBx6JQr/GNai0UdfR7DvYk6QlPkYou7pX+6HZNsAGYeY4TsSuy3mMoM2x5xMFiJ0yriye7RJzfDAPOArQ+43ZhvY9nV0YI6sjGmBnKw4CUPsVrAZqvE4Kqmq3pPWMuG/Y5M44liVcrsu/ksTw5m8hBsPgansNvzbhiLfEBUi2el8L9Ado1sRUV1x1oZNpNyi/Lyb7sWiZdZ+O5dPc782WpbsHOAjEJTYiJdQ0gm6DV8Le8hlWcHlbnBIc7KyIUfgxSxltA8WcLBMuKNqwkxD3FsoxT51GVcYQQVVVdlBhAC1cMUJjCich6c78YYdBrFI9AKq3ca/B2MKWiLKht56dTh658PyHMhw8emXG1dM2V2j/1bEn52i601bJoTNMKm9j5c3G3owPM4Jobsp58JaW8IJbKFpl/ng+KhX/DQAjr/ENJxtPrjYDcUqvkhd4pRffR3+a+M04meL6GPPI/7wSVq3mEDRcwtSjcktcFgXxrAPoux1M2le5JlxZ/CGA0xrP+Kj3zVvFnmhIwvY1iQSGKkKlvAtimTW1k3Z+sfzRQTFFN+2ZA5dPpnkI1Tu1OmsHWDJSWqNzcYuyxu0IQRYmRweCSbftVZOi8F6MJ+Y39eAGL7tAj4pbR2eR2xYziAizkeckfuAcgakLzkROCBZHacusU5V01Q=
  on:
    branch: master
    tags: true
